/* Fetch Categories */
export const FETCH_CATEGORIES = "CATEGORY/FETCH_CATEGORIES";

export const REQUESTED_CATEGORIES = "CATEGORY/REQUESTED_CATEGORIES";
export const REQUESTED_CATEGORIES_SUCCEEDED =
  "CATEGORY/REQUESTED_CATEGORIES_SUCCEEDED";
export const REQUESTED_CATEGORIES_FAILED =
  "CATEGORY/REQUESTED_CATEGORIES_FAILED";

export const CLEAR_CATEGORIES = "CATEGORY/CLEAR_CATEGORIES";
